import type { Moment } from "@/types/dj";

export const DEFAULT_MOMENTS: Moment[] = [
  {
    id: "ceremony-prelude",
    label: "Ceremony Prelude",
    emoji: "🎼",
    description: "Background music as guests are seated",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "processional",
    label: "Processional",
    emoji: "💐",
    description: "Wedding party walks down the aisle",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "bride-entrance",
    label: "Bride Entrance",
    emoji: "👰",
    description: "The bride's grand walk down the aisle",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "recessional",
    label: "Recessional",
    emoji: "🎉",
    description: "Couple exits as newlyweds",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "cocktail-hour",
    label: "Cocktail Hour",
    emoji: "🥂",
    description: "Relaxed background music during cocktails",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "grand-entrance",
    label: "Grand Entrance",
    emoji: "✨",
    description: "Couple enters the reception",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "first-dance",
    label: "First Dance",
    emoji: "💃",
    description: "The couple's first dance together",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "dinner",
    label: "Dinner",
    emoji: "🍽️",
    description: "Ambient music during the reception dinner",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "cake-cutting",
    label: "Cake Cutting",
    emoji: "🎂",
    description: "Music for the cake cutting moment",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "party-time",
    label: "Party Time",
    emoji: "🪩",
    description: "Dance floor is open — high energy!",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
  {
    id: "last-dance",
    label: "Last Dance",
    emoji: "🌙",
    description: "The final song of the night",
    songs: [],
    playlistName: "",
    djNotes: "",
  },
];
